# fly.toml app configuration file generated for api-withered-water-2633 on 2024-07-24T16:42:21+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-withered-water-2633'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NODE_ENV = "production"
  PORT = "3000"
  HOST = "0.0.0.0"
  CLERK_PUBLISHABLE_KEY = "pk_test_d2FudGVkLXJlaW5kZWVyLTY5LmNsZXJrLmFjY291bnRzLmRldiQ"

[deploy]
  release_command = "npm run db:migrate"