name: Deploy Admin
on:
  push:
    branches: [production]
    paths:
      - "admin/**"
jobs:
  deploy-admin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./admin
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.ADMIN_FLY_API_TOKEN }}
